title: Fujin Wang's Homepage
page-top-title: Fujin Wang
top-section-bg-text: Welcome to my homepage
home-subtitle: FujinWang&ensp;|&ensp;王福金
copyright-text: '&copy; Fujin Wang 2025-2026. All Rights Reserved.'
